### ISSUE TITLE
Server version error

### ISSUE THREAD

**Issue by SOG-web** [horvbalint/surreal-ts#6]
`npx surreal-ts@latest -c http://127.0.0.1:8000/rpc -u root -p root -s -o "./generated.ts" -n test -d test_db`
Error: server version `2.0.3` does not match the range supported by the client `>=1.0.0, <2.0.0`

Caused by:
    server version `2.0.3` does not match the range supported by the client `>=1.0.0, <2.0.0`

**Comment by horvbalint** [comment]
Thank you for the issue!
Last night I pushed the new version to main, but did not make the release for 2.0.0, so the readme stating that v2 is supported was not correct.
I did release v2 now, so you should not get the error above anymore🎉

Please read the release notes though for an important notice of the current capabilities of v2.0.0: https://github.com/horvbalint/surreal-ts/releases/tag/v2.0.0
