### ISSUE TITLE
[Windows] I'm not able to make this package work

### ISSUE THREAD

**Issue by Nipodemos** [horvbalint/surreal-ts#8]
Hello!
I saw your post on the surrealdb discord about this package and decided to try it out.

As stated in the title, i'm struggling to make it work, so far it hasn't generated any types besides de default ones.

I've created a minimal repo that can reproduce the issue.

How to reproduce:

* clone this repo: https://github.com/Nipodemos/surrealtsbugreport
* i've used bun the install your npm package, don't know if it matters
* open you local surrealdb server, create a namespace called `test` and a database called `surrealtsdb`
* search for the `database.surql` file in the repo to get a basic table for the database and run it on surrealist
* run the command `bun generatetypes`, which is a script on package.json
* see the `db.ts` generated file, does not mention anywhere about the user table

my database is by default on localhost:8000
my user and password is root and root, since is the default on you package i didn't include in the command

I'm on windows 10 home v22h2
only tested using bun

tested on other database and it didn't work too

**Comment by horvbalint** [comment]
Thank you for the detailed issue description!

I haven't tested surreal-ts with bun nor windows (I am on Linux), so those seem suspicious. I followed your steps with bun, and successfully generated the types for the User table, so bun is not the problem.

I will create a Windows virtual machine later today, and see if I can reproduce the issue there.

**Comment by Nipodemos** [comment]
ok thanks!

just so you know, I also wasn't able to define the config file location, nor the output location, whenever I used any of those two commands, it would error `the system cannot find the specified path (os error 3)`

Ps: the error message wording can be slightly different because my windows is in portuguese and I just translated the error

Ps²: this is less urgent in my opinion since as soon as the first problem is resolved I will be able to use the package without those two commands

**Comment by horvbalint** [comment]
I managed to get the Windows installation working 😅

The partly sad news is that "it works on my machine", still I think I know what the problem might be. SurrealDB is handling namespaces and databases very flexible and does not complain if a non-existent namespace/database is used. 
When this happened surreal-ts generated an empty file, because SurrealDB reported no error for the ns/db name.

I published a new version (3.0.0-beta.1) which will exit with an error message if this happens.
Could you try running this new version and check if it gives and error?

Maybe there is a typo in your ns/db names in the database?

**Comment by Nipodemos** [comment]
sure i'll test it tonight

**Comment by Nipodemos** [comment]
sorry for the delay, I ended up forgetting this completly.

Just tested and is as you said, it worked perfectly now. My theory is that surrealist didn't create the database even when it showed on interface that it did created, but at this point I'll doubt everything.

anyway, thanks for the reply and for the awesome package
